#!/usr/bin/env bash
# Make the NVIDIA runtime the K3s default and expose nvidia.com/gpu on a HiL host.
# cspell:ignore dropin runtimeclass
set -o errexit -o nounset -o pipefail

# Resolve repository paths and load shared helpers plus the pinned local K3s defaults.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || (cd "$SCRIPT_DIR/../../.." && pwd))"
# shellcheck source=../../../scripts/lib/common.sh
source "$REPO_ROOT/scripts/lib/common.sh"
# shellcheck source=../defaults.conf
source "$SCRIPT_DIR/../defaults.conf"

K3S_DROPIN_DIR=/etc/rancher/k3s/config.yaml.d
K3S_DROPIN="$K3S_DROPIN_DIR/10-nvidia-default-runtime.yaml"
DROPIN_CONTENT=$'# Generated by 05-enable-k3s-gpu.sh\ndefault-runtime: nvidia'

show_help() {
  cat << EOF
Usage: $(basename "$0") [OPTIONS]

Make the NVIDIA container runtime the K3s default and install the NVIDIA device
plugin, so pods without a runtime class, such as Azure ML jobs, can use GPUs.
Run it on the HiL host after 01-install-k3s.sh. When K3s already uses the nvidia
default runtime, for example after 01-install-k3s.sh --default-runtime nvidia,
the script leaves K3s running and installs only the device plugin.

Prerequisites: a working NVIDIA driver (nvidia-smi) and the NVIDIA Container
Toolkit, installed before K3s last started so K3s registered the nvidia runtime.

K3s restarts when the default runtime changes, which briefly interrupts the
host's pods. Reruns that change nothing don't restart K3s.

OPTIONS:
    -h, --help               Show this help message
    --kubeconfig PATH        Operator kubeconfig (default: $kubeconfig)
    --context NAME           Kubeconfig context (default: $EDGE_K3S_CONTEXT)
    --data-dir DIR           K3s data directory (default: $EDGE_K3S_DATA_DIR)
    --config-preview         Print prerequisite results and configuration, then exit

EXAMPLES:
    $(basename "$0") --config-preview
    $(basename "$0")
EOF
}

# Defaults
kubeconfig="${HIL_KUBECONFIG:-${XDG_DATA_HOME:-$HOME/.local/share}/physical-ai-toolchain/hil/kubeconfig.yaml}"
context="$EDGE_K3S_CONTEXT"
data_dir="$EDGE_K3S_DATA_DIR"
register_timeout="${GPU_PLUGIN_REGISTER_TIMEOUT:-180}"
config_preview=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)          show_help; exit 0 ;;
    --kubeconfig)       kubeconfig="$2"; shift 2 ;;
    --context)          context="$2"; shift 2 ;;
    --data-dir)         data_dir="$2"; shift 2 ;;
    --config-preview)   config_preview=true; shift ;;
    *)                  fatal "Unknown option: $1" ;;
  esac
done

require_tools kubectl sudo systemctl

#------------------------------------------------------------------------------
# Gather Configuration
#------------------------------------------------------------------------------

containerd_config="$data_dir/agent/etc/containerd/config.toml"

kube() {
  kubectl --kubeconfig "$kubeconfig" --context "$context" "$@"
}

# K3s regenerates the containerd config on every start from its config files, so this
# reflects the default runtime K3s actually applied.
nvidia_is_default_runtime() {
  sudo grep -q -E "default_runtime_name = ['\"]nvidia['\"]" "$containerd_config"
}

# Check every prerequisite so one run reports everything that's missing.
check_names=()
check_results=()
check_fixes=()
check() {
  local name="$1" fix="$2"
  shift 2
  check_names+=("$name")
  if "$@" >/dev/null 2>&1; then
    check_results+=("ok")
  else
    check_results+=("missing")
  fi
  check_fixes+=("$fix")
}
check "NVIDIA driver (nvidia-smi)" "Install the NVIDIA driver and confirm nvidia-smi lists the GPU" \
  nvidia-smi -L
check "NVIDIA Container Toolkit" "Install the NVIDIA Container Toolkit (nvidia-container-runtime)" \
  command -v nvidia-container-runtime
check "K3s service" "Install K3s with 01-install-k3s.sh" \
  systemctl is-active --quiet k3s
check "K3s API ($context)" "Check --kubeconfig and --context; 01-install-k3s.sh writes them" \
  kube get --raw=/readyz
check "nvidia RuntimeClass" "Restart K3s after installing the toolkit so it registers the nvidia runtime" \
  kube get runtimeclass nvidia

checks_passed=true
for i in "${!check_names[@]}"; do
  [[ "${check_results[$i]}" == "ok" ]] || checks_passed=false
done

print_checks() {
  local i
  for i in "${!check_names[@]}"; do
    print_kv "${check_names[$i]}" "${check_results[$i]}"
  done
}

if [[ "$config_preview" == "true" ]]; then
  section "Configuration Preview"
  print_kv "Kubeconfig" "$kubeconfig"
  print_kv "Context" "$context"
  print_kv "K3s Drop-in" "$K3S_DROPIN"
  print_kv "Containerd Config" "$containerd_config"
  print_kv "Device Plugin" "$DEFAULT_NVIDIA_DEVICE_PLUGIN_IMAGE"
  runtime_state="unknown; sudo needs a password"
  if sudo -n true 2>/dev/null; then
    if nvidia_is_default_runtime 2>/dev/null; then
      runtime_state="nvidia; K3s keeps running"
    else
      runtime_state="not nvidia; the run restarts K3s"
    fi
  fi
  print_kv "Default Runtime" "$runtime_state"
  section "Prerequisites"
  print_checks
  warn "Changing the default runtime restarts K3s, which briefly interrupts the host's pods."
  info "Config preview mode — exiting without changes."
  exit 0
fi

if [[ "$checks_passed" != "true" ]]; then
  section "Prerequisites"
  print_checks
  for i in "${!check_names[@]}"; do
    [[ "${check_results[$i]}" == "ok" ]] || error "${check_names[$i]}: ${check_fixes[$i]}"
  done
  fatal "Prerequisites missing; fix them and rerun"
fi

#------------------------------------------------------------------------------
# Configure the Default Container Runtime
#------------------------------------------------------------------------------
section "Configure the Default Container Runtime"

sudo test -f "$containerd_config" || fatal "K3s containerd config not found at $containerd_config; check --data-dir"
sudo grep -q 'nvidia-container-runtime' "$containerd_config" || \
  fatal "K3s didn't detect the NVIDIA runtime; confirm nvidia-container-runtime is on PATH and restart K3s"

# InstanceTypes can't set a runtime class, so Azure ML pods only reach the GPU when
# nvidia is the default runtime. Set it through a K3s config drop-in unless K3s already
# applies it.
runtime_changed=false
if nvidia_is_default_runtime; then
  info "K3s already uses nvidia as the default runtime"
else
  if [[ "$(sudo cat "$K3S_DROPIN" 2>/dev/null || true)" != "$DROPIN_CONTENT" ]]; then
    sudo install -d -m 0755 "$K3S_DROPIN_DIR"
    printf '%s\n' "$DROPIN_CONTENT" | sudo tee "$K3S_DROPIN" > /dev/null
  fi
  runtime_changed=true
  info "Restarting K3s to apply the default runtime..."
  sudo systemctl restart k3s
  for _ in $(seq 1 60); do
    kube get --raw=/readyz &>/dev/null && break
    sleep 3
  done
  kube wait --for=condition=Ready node --all --timeout=180s
  nvidia_is_default_runtime || fatal "K3s didn't apply the nvidia default runtime; inspect $containerd_config"
fi
info "Containerd default runtime is nvidia"

#------------------------------------------------------------------------------
# Install the NVIDIA Device Plugin
#------------------------------------------------------------------------------
section "Install the NVIDIA Device Plugin"

kube apply -f - << EOF
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      containers:
        - name: nvidia-device-plugin-ctr
          image: ${DEFAULT_NVIDIA_DEVICE_PLUGIN_IMAGE}
          env:
            - name: FAIL_ON_INIT_ERROR
              value: "true"
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
EOF

# A plugin pod created before the runtime change keeps its original sandbox across
# restarts and never reaches the GPU, so recreate it under the new default runtime.
if [[ "$runtime_changed" == "true" ]]; then
  kube delete pod --namespace kube-system --selector name=nvidia-device-plugin-ds --ignore-not-found
fi
kube rollout status daemonset/nvidia-device-plugin-daemonset --namespace kube-system \
  --timeout="${register_timeout}s"

#------------------------------------------------------------------------------
# Wait for GPU Registration
#------------------------------------------------------------------------------
section "Wait for nvidia.com/gpu"

node=$(kube get nodes -o jsonpath='{.items[0].metadata.name}')
elapsed=0
while :; do
  gpu_allocatable=$(kube get node "$node" -o jsonpath='{.status.allocatable.nvidia\.com/gpu}' 2>/dev/null || true)
  [[ -n "$gpu_allocatable" && "$gpu_allocatable" != "0" ]] && break
  if (( elapsed >= register_timeout )); then
    kube logs --namespace kube-system --selector name=nvidia-device-plugin-ds --tail=50 >&2 || true
    fatal "Timed out after ${register_timeout}s waiting for nvidia.com/gpu; raise GPU_PLUGIN_REGISTER_TIMEOUT"
  fi
  info "Waiting for the device plugin to register nvidia.com/gpu (${elapsed}s/${register_timeout}s)"
  sleep 5
  elapsed=$((elapsed + 5))
done

#------------------------------------------------------------------------------
# Summary
#------------------------------------------------------------------------------
section "Deployment Summary"
print_kv "Context" "$context"
print_kv "Node" "$node"
print_kv "Default Runtime" "nvidia ($([[ "$runtime_changed" == "true" ]] && echo 'changed; K3s restarted' || echo 'unchanged'))"
print_kv "Device Plugin" "$DEFAULT_NVIDIA_DEVICE_PLUGIN_IMAGE"
print_kv "Allocatable nvidia.com/gpu" "$gpu_allocatable"
info "GPUs are available to pods on this host, including Azure ML jobs"
