# EXAMPLE FOR USING AN ALTERNATIVE PYTHON FEED WITH ASTRAL UV
FROM python:3.12-slim@sha256:2f17fc044b579bab302c2e8054d3a686e2cb9a83de48e70534b94cd8ebbe06a9

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN --mount=type=secret,id=PIP_INDEX_URL \
	export PIP_INDEX_URL="$(cat /run/secrets/PIP_INDEX_URL 2>/dev/null || true)"; \
	pip install --no-cache-dir kubernetes==35.0.0 PyYAML==6.0.2

COPY . /app

RUN adduser --disabled-password --gecos "" appuser || true
USER appuser

EXPOSE 8443

CMD ["python3", "/app/mutate.py", "--host", "0.0.0.0", "--port", "8443"]
