---
apiVersion: arccontainerstorage.azure.net/v1
kind: EdgeIngestPolicy
metadata:
  name: ${ACSA_INGEST_POLICY_NAME}
  namespace: ${EDGE_NAMESPACE}
spec:
  ingest:
    order: ${ACSA_INGEST_ORDER}
    minDelaySec: ${ACSA_INGEST_MIN_DELAY_SEC}
  eviction:
    order: ${ACSA_EVICTION_ORDER}
    minDelaySec: ${ACSA_EVICTION_MIN_DELAY_SEC}
