---
apiVersion: arccontainerstorage.azure.net/v1
kind: EdgeSubvolume
metadata:
  name: ${SUBVOLUME_NAME}
  namespace: ${EDGE_NAMESPACE}
spec:
  edgevolume: ${ACSA_PVC_NAME}
  path: ${SUBVOLUME_PATH}
  auth:
    authType: MANAGED_IDENTITY
  storageaccountendpoint: "https://${STORAGE_ACCOUNT_NAME}.blob.core.windows.net/"
  container: ${BLOB_CONTAINER_NAME}
  ingestPolicy: ${ACSA_INGEST_POLICY}
