// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: MIT

import fs from 'node:fs';
import path from 'node:path';

import type { FullConfig, Reporter, Suite } from '@playwright/test/reporter';
import contentDiscovery from '../scripts/content-discovery.cjs';

const { normalizeRoute, sourceDocumentIdentity } = contentDiscovery;
export { normalizeRoute };

const buildDirectory = path.resolve(process.cwd(), 'build');
const manifestPath = path.join(buildDirectory, 'deployed-routes.json');

interface DeployedRouteManifest {
  schemaVersion: 1;
  baseUrl: string;
  routes: string[];
  exclusions: Array<{ path: string; reason: string }>;
}

interface DocsOptions {
  exclude: string[];
  path: string;
  routeBasePath: string;
  sidebarPath: string | false;
}

interface SourceFile {
  contents: string;
  relativePath: string;
}

interface SidebarItem {
  dirName?: string;
  id?: string;
  items?: SidebarItem[];
  link?: { id?: string; type?: string };
  type?: string;
}

export interface SourceDocument {
  id: string;
  relativePath: string;
  route: string;
}

export interface TierRoute {
  docId: string;
  route: string;
}

export interface SourceDiscovery {
  baseUrl: string;
  documents: SourceDocument[];
  docsOptions: DocsOptions;
  sidebarItems: SidebarItem[];
  siteConfig: Record<string, unknown>;
}

function collectHtmlFiles(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = path.join(directory, entry.name);
    return entry.isDirectory() ? collectHtmlFiles(absolutePath) : [absolutePath];
  });
}

function toRoute(filePath: string, directory = buildDirectory): string | null {
  const relativePath = path.relative(directory, filePath).replaceAll('\\', '/');
  if (relativePath === '404.html') {
    return null;
  }
  if (relativePath === 'index.html') {
    return '/';
  }
  if (relativePath.endsWith('/index.html')) {
    return `/${relativePath.slice(0, -'index.html'.length)}`;
  }
  return relativePath.endsWith('.html') ? `/${relativePath.slice(0, -'.html'.length)}` : null;
}

export function createSourceDocumentInventory(
  files: SourceFile[],
  routeBasePath = '/',
): SourceDocument[] {
  const documents = files.map(({ contents, relativePath }) =>
    sourceDocumentIdentity(relativePath, contents, routeBasePath),
  );

  const duplicateIds = documents.filter((document, index) =>
    documents.findIndex((candidate) => candidate.id === document.id) !== index,
  );
  const duplicateRoutes = documents.filter((document, index) =>
    documents.findIndex((candidate) => candidate.route === document.route) !== index,
  );
  if (duplicateIds.length > 0 || duplicateRoutes.length > 0) {
    throw new Error(
      `authored document inventory has duplicate IDs or routes: ${[
        ...duplicateIds.map(({ id }) => id),
        ...duplicateRoutes.map(({ route }) => route),
      ].join(', ')}`,
    );
  }
  return documents.sort((left, right) => left.id.localeCompare(right.id));
}

function collectSidebarIds(item: SidebarItem, documents: SourceDocument[], ids: Set<string>): void {
  if (item.type === 'doc' && item.id) {
    ids.add(item.id);
  }
  if (item.link?.type === 'doc' && item.link.id) {
    ids.add(item.link.id);
  }
  if (item.type === 'autogenerated' && item.dirName) {
    const prefix = `${item.dirName.replace(/\/$/, '')}/`;
    documents
      .filter(({ relativePath }) => relativePath.startsWith(prefix))
      .forEach(({ id }) => ids.add(id));
  }
  item.items?.forEach((child) => collectSidebarIds(child, documents, ids));
}

export function validateSidebarOwnership(
  documents: SourceDocument[],
  sidebarItems: SidebarItem[],
): string[] {
  const owners = new Map<string, Set<number>>();
  sidebarItems.forEach((item, topLevelIndex) => {
    const ids = new Set<string>();
    collectSidebarIds(item, documents, ids);
    ids.forEach((id) => {
      const documentOwners = owners.get(id) ?? new Set<number>();
      documentOwners.add(topLevelIndex);
      owners.set(id, documentOwners);
    });
  });

  const sourceIds = new Set(documents.map(({ id }) => id));
  const failures = [...owners.keys()]
    .filter((id) => !sourceIds.has(id))
    .map((id) => `sidebar references unknown document ID ${id}`);
  for (const { id } of documents) {
    const count = owners.get(id)?.size ?? 0;
    if (count !== 1) {
      failures.push(`${id} must have exactly one top-level sidebar owner; found ${count}`);
    }
  }
  return failures;
}

export function collectBuiltRoutes(directory = buildDirectory): string[] {
  return collectHtmlFiles(directory)
    .map((filePath) => toRoute(filePath, directory))
    .filter((route): route is string => route !== null)
    .map((route) => normalizeRoute(route))
    .sort();
}

export function collectSearchRoutes(searchIndex: unknown, baseUrl: string): string[] {
  if (!Array.isArray(searchIndex)) {
    throw new Error('search index must be an array');
  }
  const routes = new Set<string>();
  for (const shard of searchIndex) {
    if (!shard || typeof shard !== 'object' || !Array.isArray((shard as { documents?: unknown }).documents)) {
      throw new Error('search index shard must contain a documents array');
    }
    for (const document of (shard as { documents: unknown[] }).documents) {
      const url = (document as { u?: unknown })?.u;
      if (typeof url !== 'string') {
        throw new Error('search index document must contain a string URL');
      }
      routes.add(normalizeRoute(url, baseUrl));
    }
  }
  return [...routes].sort();
}

export function validateRouteSets(
  documents: SourceDocument[],
  builtRoutes: string[],
  searchRoutes: string[],
): string[] {
  const source = new Set(documents.map(({ route }) => normalizeRoute(route)));
  const built = new Set(builtRoutes.map((route) => normalizeRoute(route)));
  const search = new Set(searchRoutes.map((route) => normalizeRoute(route)));
  const failures: string[] = [];
  for (const route of source) {
    if (!built.has(route)) {
      failures.push(`authored route is missing from build: ${route}`);
    }
    if (!search.has(route)) {
      failures.push(`authored route is missing from search: ${route}`);
    }
  }
  for (const route of search) {
    if (!source.has(route)) {
      failures.push(`search contains unexpected route: ${route}`);
    }
  }
  return failures;
}

export function validateTierRoutes(documents: SourceDocument[], tiers: TierRoute[]): string[] {
  const byId = new Map(documents.map((document) => [document.id, document]));
  return tiers.flatMap(({ docId, route }) => {
    const document = byId.get(docId);
    if (!document) {
      return [`tier route references unknown document ID ${docId}`];
    }
    return document.route === normalizeRoute(route)
      ? []
      : [`tier route ${route} does not match ${docId} source route ${document.route}`];
  });
}

function getDocsOptions(siteConfig: Record<string, unknown>): DocsOptions {
  const presets = siteConfig.presets;
  const classic = Array.isArray(presets)
    ? presets.find((preset) => Array.isArray(preset) && preset[0] === 'classic')
    : null;
  const docs = classic?.[1]?.docs;
  if (!docs || typeof docs !== 'object' || typeof docs.path !== 'string') {
    throw new Error('classic preset must provide docs options with a source path');
  }
  if (docs.sidebarPath !== false && typeof docs.sidebarPath !== 'string') {
    throw new Error('docs sidebarPath must be a string');
  }
  return {
    exclude: Array.isArray(docs.exclude) && docs.exclude.every((pattern: unknown) => typeof pattern === 'string')
      ? docs.exclude
      : [],
    path: docs.path,
    routeBasePath: typeof docs.routeBasePath === 'string' ? docs.routeBasePath : 'docs',
    sidebarPath: docs.sidebarPath,
  };
}

function collectSourceFiles(directory: string, docsOptions: DocsOptions): SourceFile[] {
  function collect(currentDirectory: string): SourceFile[] {
    return fs.readdirSync(currentDirectory, { withFileTypes: true }).flatMap((entry) => {
      const absolutePath = path.join(currentDirectory, entry.name);
      const relativePath = path.relative(directory, absolutePath).replaceAll('\\', '/');
      if (entry.name.startsWith('.')) {
        return [];
      }
      if (entry.isDirectory()) {
        const excluded = docsOptions.exclude.some((pattern) =>
          path.matchesGlob(`${relativePath}/inventory.md`, pattern),
        );
        return excluded ? [] : collect(absolutePath);
      }
      if (!/\.(md|mdx)$/.test(entry.name)) {
        return [];
      }
      if (docsOptions.exclude.some((pattern) => path.matchesGlob(relativePath, pattern))) {
        return [];
      }
      return [{ contents: fs.readFileSync(absolutePath, 'utf8'), relativePath }];
    });
  }

  return collect(directory);
}

export async function loadSourceDiscovery(siteDirectory = process.cwd()): Promise<SourceDiscovery> {
  const { loadSiteConfig } = await import('@docusaurus/core/lib/server/config.js');
  const { loadSidebarsFile } = await import('@docusaurus/plugin-content-docs/lib/sidebars/index.js');
  const { siteConfig } = await loadSiteConfig({ siteDir: siteDirectory });
  const docsOptions = getDocsOptions(siteConfig as Record<string, unknown>);
  if (docsOptions.sidebarPath === false) {
    throw new Error('docs sidebarPath is required for ownership validation');
  }
  const docsDirectory = path.resolve(siteDirectory, docsOptions.path);
  const sidebars = await loadSidebarsFile(path.resolve(siteDirectory, docsOptions.sidebarPath));
  const sidebarItems = sidebars.docsSidebar;
  if (!Array.isArray(sidebarItems)) {
    throw new Error('docsSidebar must be an array');
  }
  return {
    baseUrl: String(siteConfig.baseUrl),
    documents: createSourceDocumentInventory(collectSourceFiles(docsDirectory, docsOptions), docsOptions.routeBasePath),
    docsOptions,
    sidebarItems: sidebarItems as SidebarItem[],
    siteConfig: siteConfig as unknown as Record<string, unknown>,
  };
}

export function readDeployedRouteManifest(): DeployedRouteManifest {
  if (!fs.existsSync(manifestPath)) {
    throw new Error(`Deployed route manifest is missing: ${manifestPath}`);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as Partial<DeployedRouteManifest>;
  if (
    manifest.schemaVersion !== 1 ||
    typeof manifest.baseUrl !== 'string' ||
    !Array.isArray(manifest.routes) ||
    !manifest.routes.every((route) => typeof route === 'string') ||
    !Array.isArray(manifest.exclusions) ||
    !manifest.exclusions.every(
      (entry) => typeof entry?.path === 'string' && typeof entry?.reason === 'string',
    )
  ) {
    throw new Error(`Deployed route manifest has an unsupported schema: ${manifestPath}`);
  }
  const sortedRoutes = [...manifest.routes].sort();
  if (new Set(sortedRoutes).size !== sortedRoutes.length || sortedRoutes.some((route, index) => route !== manifest.routes?.[index])) {
    throw new Error(`Deployed route manifest routes must be unique and sorted: ${manifestPath}`);
  }
  return manifest as DeployedRouteManifest;
}

export class ResolvedCaseBudgetReporter implements Reporter {
  onBegin(_config: FullConfig, suite: Suite): void {
    const resolvedCases = suite.allTests().length;
    console.log(`Resolved Playwright cases: ${resolvedCases}`);
  }
}

export const deployedRouteManifestPath = manifestPath;

export default ResolvedCaseBudgetReporter;