#!/usr/bin/env pwsh
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT

#Requires -Version 7.0
#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0' }
#Requires -Modules powershell-yaml

BeforeAll {
    $script:configPath = Join-Path $PSScriptRoot '../../../' '.terraform-docs.yml' | Resolve-Path
    $script:config = Get-Content $script:configPath -Raw | ConvertFrom-Yaml
}

Describe '.terraform-docs.yml Configuration' -Tag 'Unit' {
    Context 'File existence and structure' {
        It 'Should exist at repository root' {
            $script:configPath | Should -Exist
        }

        It 'Should be valid YAML' {
            $script:config | Should -Not -BeNullOrEmpty
        }
    }

    Context 'Formatter settings' {
        It 'Should use markdown table formatter' {
            $script:config.formatter | Should -Be 'markdown table'
        }

        It 'Should specify a version constraint' {
            $script:config.version | Should -Not -BeNullOrEmpty
        }
    }

    Context 'Output settings' {
        It 'Should use replace mode' {
            $script:config.output.mode | Should -Be 'replace'
        }

        It 'Should target TERRAFORM.md' {
            $script:config.output.file | Should -Be 'TERRAFORM.md'
        }

        It 'Should use simple content passthrough' {
            $script:config.output.template | Should -Match '\{\{\s*\.Content\s*\}\}'
        }
    }

    Context 'Lint compliance settings' {
        It 'Should disable HTML anchors for MD033 compliance' {
            $script:config.settings.anchor | Should -BeFalse
        }

        It 'Should disable HTML output for MD033 compliance' {
            $script:config.settings.html | Should -BeFalse
        }

        It 'Should enable escape for MD034 compliance' {
            $script:config.settings.escape | Should -BeTrue
        }
    }

    Context 'Content template' {
        It 'Should define a content template' {
            $script:config.content | Should -Not -BeNullOrEmpty
        }

        It 'Should use header-from main.tf' {
            $script:config.'header-from' | Should -Be 'main.tf'
        }

        It 'Should hide empty sections' {
            $script:config.settings.'hide-empty' | Should -BeTrue
        }

        It 'Should include BEGIN_TF_DOCS marker' {
            $script:config.content | Should -Match 'BEGIN_TF_DOCS'
        }

        It 'Should include YAML frontmatter block' {
            $script:config.content | Should -Match 'title:'
            $script:config.content | Should -Match 'description:'
            $script:config.content | Should -Match 'ms\.date:'
        }

        It 'Should include auto-generated footer' {
            $script:config.content | Should -Match 'Auto-generated by.*terraform-docs'
        }
    }

    Context 'Sort configuration' {
        It 'Should enable sorting' {
            $script:config.sort.enabled | Should -BeTrue
        }

        It 'Should sort by required' {
            $script:config.sort.by | Should -Be 'required'
        }
    }
}
